---
bibliography: references.bib
---

# A Digital Complutensian Bible

> *Multilingual reading for all in a digital environment*.

## Overview

This project is developing a digital multilingual Bible modelled on [the sixteenth-century Complutensian Polyglot](./complutensian/). The Complutensian included numerous aids for "those who do not have a perfect command of (each) language"[^1] while pushing the limits of print technology to support novel kinds of scholarly research.[^2] Its six volumes supported:

[^1]: In the words of the editors' preface: *qui non integram linguae cognitionem adepti sunt*

[^2]: Again, this is the editors' explicit aim: *studiosis vtillisimum fore credimus*

1.  comparative, multilingual reading of texts
2.  lemmatization coordinating texts and lexica
3.  morpho-syntactic alignment for cross-lingual analysis

We are implementing the same kinds of functionality digitally, to explore ways we can support the Complutensian's goals of aiding those without extensive background in the Biblical languages, and facilitating innovative cross-lingual scholarship.

## See more about...

-   the [original Complutensian Bible](./complutensian/)
-   the [digital resources we're creating](./resources/)
-   things we're doing with [our digital polyglot](./examples/)

## Presentations

- [AIA/SCS](./presentations/aia-scs2025/) (Philadelphia, January, 2025)
- [Society of Biblical Literature](./presentations/sbl2024/) (San Diego, November, 2024)

