---
title: Who we are
---


- Neel Smith, Professor Emeritus, Department of Classics, College of the Holy Cross.

> I am an emeritus professor at the College of the Holy Cross. I'm especially interested in studying ancient texts using computational approaches that take account of both the textual contents and the non-textual features of physical artifacts, such as page layout, organization of contents in tabular structures, graphic elements like mathematical figures, or non-textual notation such as musical notation. See my site on [quarto.pub](https://neelsmith.quarto.pub) for some of [my current projects](https://neelsmith.quarto.pub/projects/), and more of [my digital scholarship](https://neelsmith.quarto.pub/digschol/).

- Ashley Terjanian, Holy Cross '26.

> I am a student in the Class of 2026 at the College of the Holy Cross studying Classics and Environmental Studies. I love learning about various realms of the ancient world, and connecting my understanding of antiquity to our current world’s environment. In the summer of 2024, I was funded by Holy Cross' Weiss Summer Research Program to work on a digital edition of the Latin glosses in the Complutensian Polyglot Bible, and study its multilingual reading structures, early modern printing practices, and ancient manuscripts.