
# Explicit statements by editors

Note that reader in these prefaces is addressed as *studiose Lector*.

Prolog to pope addresses reason and design!

## Volume 1

**Title page plus 12 pages of prefatory material (1 handwritten in BNE copy)**

- `vol1_+_2r` : Ad sanctissimum ac clementissimum dominum nostrum D. Leonem Decimum
- `vol1_+_2v` : Ad lectorem. De his que ad lectionem Ueteris testamenti diuersis linguis nunc primum impressi: sunt praenotanda
- `vol1_+_3r` : De Arte inueniendi radicem siue primitiuum cuiuisque dictionis Hebraicae
- `vol1_+_4r` : Prologus in Nouum testamentum: et de causis quare in eo apices graeci sunt praemissi. Ad lectorem.
- `vol1_+_4r` : Prologus in Hebraicum Chaldaicumque dictionarium atque Grammaticam Hebraeam cum interpretationibus propriorum nominum. Ad lectorem.
- `vol1_+_4v` : Notandum.
- `vol1_+_5r` : Modi intelligendi sacram scripturam.
- `vol1_+_5r-vol1_+_6v` : epistola beati Hieronymi ad Paulinum. *Note: chapters of this are explicitly labelled*
    - `vol1_+_6r` : Hec a me perstricta sunt breuiter. Neque enim epistolaris angustia euagari longius patiebatur
- `vol1_+_7r` : Incipit praefatio sancti Hieronymi
- `vol1_+_7v` : handwritten copy of version printed in Huntington


## Volume 2

- `vol2_title_1v` : repeats *Ad sanctissimum ac clementissimum dominum nostrum D. Leonem Decimum* from `vol1_+_2r`
- `vol2_prolog_1r` : repeats *De his que ad lectionem Ueteris testamenti diuersis linguis nunc primum impressi: sunt praenotanda* from `vol1_+_2v` but type is reset. Is text really the same?

## Volume 3

**Title page + 3 pages of prefatory material**

- `vol3_aaa_1v` : repeats *Ad sanctissimum ac clementissimum dominum nostrum D. Leonem Decimum* from `vol1_+_2r`
- `vol3_aaa_2r` : repeats *Ad lectorem. De his que ad lectionem Ueteris testamenti diuersis linguis nunc primum impressi: sunt praenotanda* from `vol1_+_2v`
- `vol3_aaa_2v` : Jerome's prolog

## Volume 4

**Title page + 3 pages of prefatory material**

- `vol4_a_1v` : repeats *Ad sanctissimum ac clementissimum dominum nostrum D. Leonem Decimum* from `vol1_+_2r`
- `vol4_a_2r` : repeats *Ad lectorem. De his que ad lectionem Ueteris testamenti diuersis linguis nunc primum impressi: sunt praenotanda* from `vol1_+_2v`
- `vol4_a_2v` : Jerome's prolog


## Volume 5

**Title page and 6 pages of prefatory material**

- `vol5_a-preface_2r` : Greek text of why no accents or breathing in Greek!  Reader is addressed ὦ σπουδαῖε φιλόλογε 
- `vol5_a-preface_2v` : Latin version of same, repeating note from volume 1 on form of Greek in NT
- `vol5_a-preface_3r` : The letter of Eusebius to Carpianus, explaining the Canones!  Explicit link to history of editing scholarly works.
- `vol5_a-preface_3v` : Jerome to Pope Damasus
- `vol5_a-preface_4r` : alius prologus
- `vol5_a-preface_4v` : argumentum

## Volume 6

**Title page and one page of introductory material.**

- `vol6_title_1v` : Cum his qui diuine legis integram cognitionem ac in ea christum qui uera sapientia est pio mentis affectu conquirunt: quam plurimum conferat earum linguarum peritia : 