---
title: Pluto notebooks
---



One technology that is a good match for exploratory small-digital scholarship is Pluto, a reactive notebook system that runs in a browser. On this page we're gathering examples of Pluto notebooks working with our datasets.

:::{.callout-note title="Pluto"}
If you're not familiar with Pluto notebooks, here's a little  [more information](./pluto-about/) about them.
:::

### Browsing source material

- a IIIF viewer to [browse images](./imagebrowsing/)

###  Navigating the Madrid copy of the Complutensian

- [navigate by quire and page](./browse-codex/) to explore  the physical organization of each volume
- [navigate by *incipit/explicit* of Biblical books](./incipit/)

### The physical organization of the Complutensian 

- [table of contents](./toc/): index of texts to images
- [passages of text indexed to browsable image](./passage-plus-image/) 


## The Complutensian's editorial practices: alignment and orthography

- [Latin spacing markers](./spacing-markers-latin/)
- usage of [abbreviations in glosses](./abbreviations/) 

### Digital editing and indexing

- validating editing: [diplomatic text and indexing to source image](./validation/index.qmd)
- validating editing: [morphological validation of normalized text](./morphology-glosses/index.qmd)

### Reading passages of texts and glosses

- browse [text passages in the four versions of the Complutensian Bible](./alignedpassages/)
- browse [text passages and associated Latin glosses](./aligned-with-glosses/)
- [paired reader](./paired-reader/)
- [citable tokens](./citable-tokens/) 


### Morphological analysis


- [morphology of the Greek Septuagint](./greek-morphology/)
- [find and identify verb forms](./greek-verbs/) for passages in Greek
- [isolate verb forms in passages of Greek](./isolate-verbs-greek/)
- [isolate verbs in Latin documents](./isolateverbs/)
- [Hebrew verbs](./hebrew-verbs/) 

### Comparing  textual contents

- [compare verbal usage in Latin glosses and Vulgate](./glossing-vocab/)
- [Zipf's law in Latin texts](./zipf-latin/): token frequencies 
- [histograms of verbs](./verbhisto/)


### Aligning features

- [align verb functions](./align-verbs-multilingual/) across languages
- [align verb usage in Latin text and glosses](./align-verbs-to-latin/)

