
## Notes on Huntington copy

In volume 1 quire `+`:

 But folios 7 - 8 are flipped from order in Madrid (and others)? These would be bifolios with a guard sheet and title page.  



**Different content in Madrid**: verso to Prolog of Jerome has handwritten text in BNE copy!  Huntington has printed text. (This is folio 7 verso in the Huntington copy, 8 verson in BNE copy)


 entire Torah in sequential quires running from `a` - `z`, (no `j`, `u`), `aa` - `zz` and two final quires with special marks. The register on the final recto notes that `Omnes sunt terni excepto ultimo qui est quaternus`. Final verso is blank but has same red frame for planned spaces as pages with content.


Vol 3
- corrigenda. 2 pages followed by a printed blank with red frames (so a binion) with intial recto identified as `a`.


Vol 5


Notes: `A ii verso` has handwritten variant in margin; `A iii recto` has interesting example of alignment extending even to word division! (Follow continuation on to `A iiii verso`)

Notes: spaces for elaborated caps saved and have regular lc version of letter printed but not replaced in many spots e.g., page alpha 1 of volume 2's travels of Paul.
