---
title: Exploring the digital polyglot
---


## A "small digital" approach

We want to faciliate multilingual reading for all, whether beginners or experts in any of the languages of the Complutensian Bible, in digital applications adapted to their needs and interests, whether or not we've even imagined the application yet. It's not possible to achieve this with a single, monolithic application. Instead, we are assembling a collection of reusable digital resources. These include data sets already created by others as well our own contributions, and specific applications using those data sets.  
   

This approach is an example of what I've elsewhere called ["small-digital" scholarship](https://neelsmith.quarto.pub/posts/2024-10-28-small-digital/index.html). We want to encourage exploratory scholarly work with minimal technical prerequisites that can be carried out by a small team or individual, is well documented and can be easily replicated.


## Platforms for sharing replicable work

- [Pluto notebooks](./pluto/)
- [Quarto](./quarto/)

