---
title: Quarto
---

[Quarto](https://quarto.org) is a publication system that lets you combine prose in Markdown's plain-text format with executable code. Quarto can generate output in many formats (web pages, camera-ready PDFs, slide stacks...), and embeds the output of code blocks in the published format. 

We can reuse exactly the same code we experiment with in [Pluto notebooks](../pluto/) in Quarto documents.

## Quarto documents we're currently developing


- slides used at the 2025 Society for Classical Studies meeting:
    - [source code](https://github.com/neelsmith/scs2025)
    - [PDF export](http://shot.holycross.edu/scs2025/smith-terjanian.pdf) of the RevealJS presentation
- slides used at the 2024 Society of Biblical Literature meeting:
    - [source code](https://github.com/neelsmith/sbl2024) for the interactive presentation using RevealJS
    - [PDF export](http://shot.holycross.edu/sbl/smith-terjanian.pdf) of the RevealJS presentation
- slides used at the 2025 Society for Classical Studies meeting
    - source code for slide stack using RevealJS
    - PDF export of the slide stack    
- forthcoming article: Neel Smith and Ashley Terjanian, "Inclusive multilingual reading five centuries after the Complutensian polyglot Bible" (source and rendered version to be added after publication, expected in 2025).
- the project web site:
    - source code on [github](https://github.com/neelsmith/complutensian-docs)
    - published as a [web site](https://neelsmith.quarto.pub/digitalcomplutensian/)